### ISSUE TITLE
Integration tests for password reset are missing

### ISSUE THREAD

**Issue by zadigus** [shopozor/consumer-frontend#17]
@comteharbour what tests did you write for the password registration? Do you have unit tests somewhere? do you test what happens when a Consumer fills the form? do you test what happens when the Consumer visits the activation link?

**Comment by zadigus** [comment]
Same [issue](https://github.com/shopozor/management-frontend/issues/30) on the management-frontend.

**Comment by comteharbour** [comment]
unit tests exist:
https://github.com/shopozor/common-frontend/blob/dev/src/pages/__tests__/ResetPassword.spec.js
